In [6]:
import numpy as np
import networkx as nx
import torch
from torch_geometric.utils import to_networkx, from_networkx
# Make the networkx graph
G = nx.Graph()

# Add some cars (just do 4 for now)
G.add_nodes_from([
      (1, {'y': 1, 'x': 0.5}),
      (2, {'y': 2, 'x': 0.2}),
      (3, {'y': 3, 'x': 0.3}),
      (4, {'y': 4, 'x': 0.1}),
      (5, {'y': 5, 'x': 0.2}),
])

# Add some edges
G.add_edges_from([
                  (1, 2), (1, 4), (1, 5),
                  (2, 3), (2, 4),
                  (3, 2), (3, 5),
                  (4, 1), (4, 2),
                  (5, 1), (5, 3)
])

# Convert the graph into PyTorch geometric
pyg_graph = from_networkx(G)

print(pyg_graph)
# Data(edge_index=[2, 12], x=[5], y=[5])
print(pyg_graph.x)
# tensor([0.5000, 0.2000, 0.3000, 0.1000, 0.2000])
print(pyg_graph.y)
# tensor([1, 2, 3, 4, 5])
print(pyg_graph.edge_index)
# tensor([[0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 4],
#         [1, 3, 4, 0, 2, 3, 1, 4, 0, 1, 0, 2]])

# Split the data 
train_ratio = 0.2
num_nodes = pyg_graph.x.shape[0]
num_train = int(num_nodes * train_ratio)
idx = [i for i in range(num_nodes)]

np.random.shuffle(idx)
train_mask = torch.full_like(pyg_graph.y, False, dtype=bool)
train_mask[idx[:num_train]] = True
test_mask = torch.full_like(pyg_graph.y, False, dtype=bool)
test_mask[idx[num_train:]] = True

print(train_mask)
# tensor([ True, False, False, False, False])
print(test_mask)
# tensor([False,  True,  True,  True,  True])

Data(x=[5], edge_index=[2, 12], y=[5])
tensor([0.5000, 0.2000, 0.3000, 0.1000, 0.2000])
tensor([1, 2, 3, 4, 5])
tensor([[0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 4],
        [1, 3, 4, 0, 2, 3, 1, 4, 0, 1, 0, 2]])
tensor([False, False, False,  True, False])
tensor([ True,  True,  True, False,  True])


In [7]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

In [15]:
data = dataset[0]
print(data)
print(data.train_mask.sum())
print(data.val_mask.sum())
print(data.test_mask.sum())

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])
tensor(140)
tensor(500)
tensor(1000)


In [23]:
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

In [2]:
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)

data_list = [i for i in dataset]
loader = DataLoader(data_list, batch_size=32, shuffle=True)
for i in loader:
    print(i)

DataBatch(edge_index=[2, 4016], x=[1067, 21], y=[32], batch=[1067], ptr=[33])
DataBatch(edge_index=[2, 3806], x=[972, 21], y=[32], batch=[972], ptr=[33])
DataBatch(edge_index=[2, 3996], x=[1045, 21], y=[32], batch=[1045], ptr=[33])
DataBatch(edge_index=[2, 3792], x=[1017, 21], y=[32], batch=[1017], ptr=[33])
DataBatch(edge_index=[2, 4122], x=[1071, 21], y=[32], batch=[1071], ptr=[33])
DataBatch(edge_index=[2, 3882], x=[990, 21], y=[32], batch=[990], ptr=[33])
DataBatch(edge_index=[2, 3698], x=[963, 21], y=[32], batch=[963], ptr=[33])
DataBatch(edge_index=[2, 3460], x=[892, 21], y=[32], batch=[892], ptr=[33])
DataBatch(edge_index=[2, 4092], x=[1122, 21], y=[32], batch=[1122], ptr=[33])
DataBatch(edge_index=[2, 3864], x=[1045, 21], y=[32], batch=[1045], ptr=[33])
DataBatch(edge_index=[2, 3886], x=[977, 21], y=[32], batch=[977], ptr=[33])
DataBatch(edge_index=[2, 3932], x=[1004, 21], y=[32], batch=[1004], ptr=[33])
DataBatch(edge_index=[2, 4130], x=[1074, 21], y=[32], batch=[1074], ptr=[3

In [9]:
import torch
a =torch.rand(10,5)
print(a)
print(a[1])
b = [1]
c = torch.tensor(b)
print(a[b])
print(a[c.repeat(5)])

tensor([[0.3381, 0.6711, 0.3586, 0.3750, 0.6673],
        [0.5826, 0.5489, 0.1666, 0.7584, 0.5811],
        [0.1094, 0.0598, 0.9345, 0.0498, 0.9743],
        [0.8946, 0.8983, 0.3115, 0.4215, 0.3810],
        [0.2878, 0.7763, 0.1963, 0.1039, 0.0451],
        [0.9691, 0.7604, 0.1078, 0.1348, 0.6553],
        [0.8809, 0.0026, 0.6332, 0.4650, 0.4761],
        [0.9440, 0.4283, 0.4445, 0.1092, 0.7236],
        [0.3010, 0.2219, 0.2635, 0.0074, 0.9433],
        [0.0693, 0.8644, 0.4994, 0.6155, 0.2066]])
tensor([0.5826, 0.5489, 0.1666, 0.7584, 0.5811])
tensor([[0.5826, 0.5489, 0.1666, 0.7584, 0.5811]])
tensor([[0.5826, 0.5489, 0.1666, 0.7584, 0.5811],
        [0.5826, 0.5489, 0.1666, 0.7584, 0.5811],
        [0.5826, 0.5489, 0.1666, 0.7584, 0.5811],
        [0.5826, 0.5489, 0.1666, 0.7584, 0.5811],
        [0.5826, 0.5489, 0.1666, 0.7584, 0.5811]])


In [27]:
import torch
with torch.autograd.set_detect_anomaly(True):
    x = torch.rand(10, 20, requires_grad=True)
    y = torch.rand(10)
    z = (x / y[:, np.newaxis])  # anomaly detection will point here
    c = y.abs_()  # but the problem is here
    z.sum().backward()

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10, 1]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

In [19]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)
print(data.x)
print(data.edge_index)
print(data.y)
print(data.num_nodes)
print(data.num_edges)
print(data.num_node_features)
print(data.has_isolated_nodes())
print(data.is_directed())
print(data.has_self_loops())

tensor([[-1.],
        [ 0.],
        [ 1.]])
tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])
None
3
4
1
False
False
False


In [28]:
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)
for batch in loader:
    print(batch, batch.num_graphs)
    #print(batch.batch)

DataBatch(edge_index=[2, 3772], x=[967, 21], y=[32], batch=[967], ptr=[33]) 32
DataBatch(edge_index=[2, 4358], x=[1100, 21], y=[32], batch=[1100], ptr=[33]) 32
DataBatch(edge_index=[2, 4200], x=[1096, 21], y=[32], batch=[1096], ptr=[33]) 32
DataBatch(edge_index=[2, 3984], x=[1060, 21], y=[32], batch=[1060], ptr=[33]) 32
DataBatch(edge_index=[2, 3944], x=[1038, 21], y=[32], batch=[1038], ptr=[33]) 32
DataBatch(edge_index=[2, 4458], x=[1147, 21], y=[32], batch=[1147], ptr=[33]) 32
DataBatch(edge_index=[2, 4208], x=[1124, 21], y=[32], batch=[1124], ptr=[33]) 32
DataBatch(edge_index=[2, 4170], x=[1151, 21], y=[32], batch=[1151], ptr=[33]) 32
DataBatch(edge_index=[2, 4054], x=[1013, 21], y=[32], batch=[1013], ptr=[33]) 32
DataBatch(edge_index=[2, 3602], x=[966, 21], y=[32], batch=[966], ptr=[33]) 32
DataBatch(edge_index=[2, 3628], x=[969, 21], y=[32], batch=[969], ptr=[33]) 32
DataBatch(edge_index=[2, 3532], x=[939, 21], y=[32], batch=[939], ptr=[33]) 32
DataBatch(edge_index=[2, 4232], x=[1

In [44]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')
loader = DataLoader(dataset)
for i in loader:
    print(type(i), i)

for i in dataset:
    print(type(i), i.num_node_features)

<class 'torch_geometric.data.batch.DataBatch'> DataBatch(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708], batch=[2708], ptr=[2])
<class 'torch_geometric.data.data.Data'> 1433


In [43]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)

In [46]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GCN().to(device)
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(200):
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()

In [47]:
model.eval()
pred = model(data).argmax(dim=1)
correct = (pred[data.test_mask] == data.y[data.test_mask]).sum()
acc = int(correct) / int(data.test_mask.sum())
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.8040
